// app/layout.tsx (Next.js 13~15 기준 App Router 구조)
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "CEOS Netflix",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex justify-center bg-neutral-900 text-white font-pretendard">
        <div className="box-border flex flex-col w-full  max-w-[375px] min-h-[812px] ">
          {children}
        </div>
      </body>
    </html>
  );
}
